-- MySQL Script generated by MySQL Workbench
-- Sun Dec 18 00:07:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `MobileNumber` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`MobileNumber`),
  UNIQUE INDEX `MobileNumber_UNIQUE` (`MobileNumber` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Quantity` VARCHAR(45) NULL,
  `Price` VARCHAR(45) NULL,
  `Stock` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `Customer_MobileNumber` INT NOT NULL,
  `Product_id` INT NOT NULL,
  `OrderId` VARCHAR(45) NOT NULL,
  `TotalBill` DECIMAL(10) NOT NULL,
  `OrderDate` DATETIME NOT NULL,
  PRIMARY KEY (`Customer_MobileNumber`, `Product_id`, `OrderId`),
  INDEX `fk_Customer_has_Product_Product1_idx` (`Product_id` ASC) VISIBLE,
  INDEX `fk_Customer_has_Product_Customer_idx` (`Customer_MobileNumber` ASC) VISIBLE,
  UNIQUE INDEX `OrderId_UNIQUE` (`OrderId` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_has_Product_Customer`
    FOREIGN KEY (`Customer_MobileNumber`)
    REFERENCES `mydb`.`Customer` (`MobileNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customer_has_Product_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `mydb`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
